---
# tasks file for ndn-cxx
- name: install base ndn libraries 
  action: >
       {{ ansible_pkg_mgr }} name={{ item }} state=latest update_cache=yes
  with_items:
       - ndn-cxx
       - ndn-cxx-dev
       - ndn-cxx-dbg

